<?php
/**
 * ExportTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SiapepFrance\KizeoForms
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kizeo REST
 *
 * This is a Swagger generated doc for Kizeo REST API 3. You can find additionnal documentation here : [Online documentation](/doc).
 *
 * OpenAPI spec version: 3.0.0
 * Contact: support@kizeo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SiapepFrance\KizeoForms;

/**
 * ExportTest Class Doc Comment
 *
 * @category    Class
 * @description Export
 * @package     SiapepFrance\KizeoForms
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ExportTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Export"
     */
    public function testExport()
    {
    }

    /**
     * Test attribute "formId"
     */
    public function testPropertyFormId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "json"
     */
    public function testPropertyJson()
    {
    }

    /**
     * Test attribute "isDefault"
     */
    public function testPropertyIsDefault()
    {
    }

    /**
     * Test attribute "deleted"
     */
    public function testPropertyDeleted()
    {
    }

    /**
     * Test attribute "computedNames"
     */
    public function testPropertyComputedNames()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }
}
