<?php
/**
 * UserTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SiapepFrance\KizeoForms
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kizeo REST
 *
 * This is a Swagger generated doc for Kizeo REST API 3. You can find additionnal documentation here : [Online documentation](/doc).
 *
 * OpenAPI spec version: 3.0.0
 * Contact: support@kizeo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SiapepFrance\KizeoForms;

/**
 * UserTest Class Doc Comment
 *
 * @category    Class
 * @description User
 * @package     SiapepFrance\KizeoForms
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UserTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "User"
     */
    public function testUser()
    {
    }

    /**
     * Test attribute "login"
     */
    public function testPropertyLogin()
    {
    }

    /**
     * Test attribute "password"
     */
    public function testPropertyPassword()
    {
    }

    /**
     * Test attribute "firstName"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "lastName"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "admin"
     */
    public function testPropertyAdmin()
    {
    }

    /**
     * Test attribute "formUser"
     */
    public function testPropertyFormUser()
    {
    }

    /**
     * Test attribute "allowFormMenu"
     */
    public function testPropertyAllowFormMenu()
    {
    }

    /**
     * Test attribute "allowExternallistMenu"
     */
    public function testPropertyAllowExternallistMenu()
    {
    }

    /**
     * Test attribute "allowUserMenu"
     */
    public function testPropertyAllowUserMenu()
    {
    }

    /**
     * Test attribute "allowApplicationMenu"
     */
    public function testPropertyAllowApplicationMenu()
    {
    }

    /**
     * Test attribute "allowExportMenu"
     */
    public function testPropertyAllowExportMenu()
    {
    }

    /**
     * Test attribute "allowDataMenu"
     */
    public function testPropertyAllowDataMenu()
    {
    }

    /**
     * Test attribute "allowAccountMenu"
     */
    public function testPropertyAllowAccountMenu()
    {
    }
}
