<?php
/**
 * DataApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SiapepFrance\KizeoForms
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kizeo REST
 *
 * This is a Swagger generated doc for Kizeo REST API 3. You can find additionnal documentation here : [Online documentation](/doc).
 *
 * OpenAPI spec version: 3.0.0
 * Contact: support@kizeo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SiapepFrance\KizeoForms;

use SiapepFrance\KizeoForms\Configuration;
use SiapepFrance\KizeoForms\ApiException;
use SiapepFrance\KizeoForms\ObjectSerializer;

/**
 * DataApiTest Class Doc Comment
 *
 * @category Class
 * @package  SiapepFrance\KizeoForms
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DataApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for formsFormIdDataAdvancedPost
     *
     * Get List of filtered data of a form (with advanced filtering options).
     *
     */
    public function testFormsFormIdDataAdvancedPost()
    {
    }

    /**
     * Test case for formsFormIdDataAllGet
     *
     * Get the list of all data of a form.
     *
     */
    public function testFormsFormIdDataAllGet()
    {
    }

    /**
     * Test case for formsFormIdDataDataIdGet
     *
     * Get data of a form.
     *
     */
    public function testFormsFormIdDataDataIdGet()
    {
    }

    /**
     * Test case for formsFormIdDataGet
     *
     * Get the list of all data of a form (not read).
     *
     */
    public function testFormsFormIdDataGet()
    {
    }

    /**
     * Test case for formsFormIdDataReadnewGet
     *
     * Get content of unread data.
     *
     */
    public function testFormsFormIdDataReadnewGet()
    {
    }

    /**
     * Test case for formsFormIdDataSearchPost
     *
     * Get List of filtered data of a form.
     *
     */
    public function testFormsFormIdDataSearchPost()
    {
    }

    /**
     * Test case for formsFormIdMarkasreadPost
     *
     * Set list of data of a form to read.
     *
     */
    public function testFormsFormIdMarkasreadPost()
    {
    }

    /**
     * Test case for formsFormIdMarkasunreadPost
     *
     * Set list of data of form to unread.
     *
     */
    public function testFormsFormIdMarkasunreadPost()
    {
    }

    /**
     * Test case for formsFormIdPushDataIdPost
     *
     * Send push with data.
     *
     */
    public function testFormsFormIdPushDataIdPost()
    {
    }

    /**
     * Test case for formsFormIdPushPost
     *
     * Send push with data.
     *
     */
    public function testFormsFormIdPushPost()
    {
    }

    /**
     * Test case for formsPushInboxGet
     *
     * Receive new pushed data.
     *
     */
    public function testFormsPushInboxGet()
    {
    }
}
