<?php
/**
 * ExportsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SiapepFrance\KizeoForms
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kizeo REST
 *
 * This is a Swagger generated doc for Kizeo REST API 3. You can find additionnal documentation here : [Online documentation](/doc).
 *
 * OpenAPI spec version: 3.0.0
 * Contact: support@kizeo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SiapepFrance\KizeoForms;

use SiapepFrance\KizeoForms\Configuration;
use SiapepFrance\KizeoForms\ApiException;
use SiapepFrance\KizeoForms\ObjectSerializer;

/**
 * ExportsApiTest Class Doc Comment
 *
 * @category Class
 * @package  SiapepFrance\KizeoForms
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ExportsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for formsFormIdDataDataIdExportsExportIdGet
     *
     * Export data.
     *
     */
    public function testFormsFormIdDataDataIdExportsExportIdGet()
    {
    }

    /**
     * Test case for formsFormIdDataDataIdExportsExportIdPdfGet
     *
     * Export data (PDF).
     *
     */
    public function testFormsFormIdDataDataIdExportsExportIdPdfGet()
    {
    }

    /**
     * Test case for formsFormIdDataDataIdFormPicturesMediaNameGet
     *
     * Get one fixed image of a form.
     *
     */
    public function testFormsFormIdDataDataIdFormPicturesMediaNameGet()
    {
    }

    /**
     * Test case for formsFormIdDataDataIdMediasMediaNameGet
     *
     * Get one image of a form.
     *
     */
    public function testFormsFormIdDataDataIdMediasMediaNameGet()
    {
    }

    /**
     * Test case for formsFormIdDataDataIdPdfGet
     *
     * Get PDF data of a form.
     *
     */
    public function testFormsFormIdDataDataIdPdfGet()
    {
    }

    /**
     * Test case for formsFormIdDataMultipleCsvCustomPost
     *
     * Get custom CSV data (multiple) of a form.
     *
     */
    public function testFormsFormIdDataMultipleCsvCustomPost()
    {
    }

    /**
     * Test case for formsFormIdDataMultipleCsvPost
     *
     * Get CSV data (multiple) of a form.
     *
     */
    public function testFormsFormIdDataMultipleCsvPost()
    {
    }

    /**
     * Test case for formsFormIdDataMultipleExcelCustomPost
     *
     * Get custom Excel list data (multiple) of a form.
     *
     */
    public function testFormsFormIdDataMultipleExcelCustomPost()
    {
    }

    /**
     * Test case for formsFormIdDataMultipleExcelPost
     *
     * Get Excel list data (multiple) of a form.
     *
     */
    public function testFormsFormIdDataMultipleExcelPost()
    {
    }

    /**
     * Test case for formsFormIdExportsGet
     *
     * Get list of Word and Excel exports.
     *
     */
    public function testFormsFormIdExportsGet()
    {
    }

    /**
     * Test case for formsFormIdMultipleDataExportsExportIdPdfPost
     *
     * Export data (multiple / PDF).
     *
     */
    public function testFormsFormIdMultipleDataExportsExportIdPdfPost()
    {
    }
}
