<?php
/**
 * GroupsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SiapepFrance\KizeoForms
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kizeo REST
 *
 * This is a Swagger generated doc for Kizeo REST API 3. You can find additionnal documentation here : [Online documentation](/doc).
 *
 * OpenAPI spec version: 3.0.0
 * Contact: support@kizeo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SiapepFrance\KizeoForms;

use SiapepFrance\KizeoForms\Configuration;
use SiapepFrance\KizeoForms\ApiException;
use SiapepFrance\KizeoForms\ObjectSerializer;

/**
 * GroupsApiTest Class Doc Comment
 *
 * @category Class
 * @package  SiapepFrance\KizeoForms
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GroupsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for groupGroupIdDelete
     *
     * Delete a group.
     *
     */
    public function testGroupGroupIdDelete()
    {
    }

    /**
     * Test case for groupGroupIdGet
     *
     * Get a group.
     *
     */
    public function testGroupGroupIdGet()
    {
    }

    /**
     * Test case for groupGroupIdLeaderLeaderIdDelete
     *
     * Remove a leader from a specific group.
     *
     */
    public function testGroupGroupIdLeaderLeaderIdDelete()
    {
    }

    /**
     * Test case for groupGroupIdLeaderLeaderIdPost
     *
     * Add a leader into a specific group.
     *
     */
    public function testGroupGroupIdLeaderLeaderIdPost()
    {
    }

    /**
     * Test case for groupGroupIdLeadersGet
     *
     * Get all groups' leaders of a specific group.
     *
     */
    public function testGroupGroupIdLeadersGet()
    {
    }

    /**
     * Test case for groupGroupIdLeadersPost
     *
     * Add several leaders into a group.
     *
     */
    public function testGroupGroupIdLeadersPost()
    {
    }

    /**
     * Test case for groupGroupIdPut
     *
     * Update a group.
     *
     */
    public function testGroupGroupIdPut()
    {
    }

    /**
     * Test case for groupGroupIdUserUserIdDelete
     *
     * Remove an user from a specific group.
     *
     */
    public function testGroupGroupIdUserUserIdDelete()
    {
    }

    /**
     * Test case for groupGroupIdUserUserIdPost
     *
     * Add an user into a specific group.
     *
     */
    public function testGroupGroupIdUserUserIdPost()
    {
    }

    /**
     * Test case for groupGroupIdUsersGet
     *
     * Get all users of a specific group.
     *
     */
    public function testGroupGroupIdUsersGet()
    {
    }

    /**
     * Test case for groupGroupIdUsersPost
     *
     * Add several users into a group.
     *
     */
    public function testGroupGroupIdUsersPost()
    {
    }

    /**
     * Test case for groupPost
     *
     * Create a new group.
     *
     */
    public function testGroupPost()
    {
    }

    /**
     * Test case for groupsGet
     *
     * Get all groups.
     *
     */
    public function testGroupsGet()
    {
    }

    /**
     * Test case for groupsOrderedGet
     *
     * Get all groups ordered.
     *
     */
    public function testGroupsOrderedGet()
    {
    }
}
