<?php
/**
 * ListsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SiapepFranceKizeoForms
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kizeo REST
 *
 * This is a Swagger generated doc for Kizeo REST API 3. You can find additionnal documentation here : [Online documentation](/doc).
 *
 * OpenAPI spec version: 3.0.0
 * Contact: support@kizeo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SiapepFranceKizeoForms;

use SiapepFranceKizeoForms\Configuration;
use SiapepFranceKizeoForms\ApiException;
use SiapepFranceKizeoForms\ObjectSerializer;

/**
 * ListsApiTest Class Doc Comment
 *
 * @category Class
 * @package  SiapepFranceKizeoForms
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ListsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for listsGet
     *
     * Get External Lists.
     *
     */
    public function testListsGet()
    {
    }

    /**
     * Test case for listsListIdCompleteGet
     *
     * Get External List Definition (Without taking in account filters).
     *
     */
    public function testListsListIdCompleteGet()
    {
    }

    /**
     * Test case for listsListIdGet
     *
     * Get External List Definition.
     *
     */
    public function testListsListIdGet()
    {
    }

    /**
     * Test case for listsListIdPut
     *
     * Update External List Definition.
     *
     */
    public function testListsListIdPut()
    {
    }
}
