<?php
/**
 * UsersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SiapepFrance\KizeoForms
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kizeo REST
 *
 * This is a Swagger generated doc for Kizeo REST API 3. You can find additionnal documentation here : [Online documentation](/doc).
 *
 * OpenAPI spec version: 3.0.0
 * Contact: support@kizeo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SiapepFrance\KizeoForms;

use SiapepFrance\KizeoForms\Configuration;
use SiapepFrance\KizeoForms\ApiException;
use SiapepFrance\KizeoForms\ObjectSerializer;

/**
 * UsersApiTest Class Doc Comment
 *
 * @category Class
 * @package  SiapepFrance\KizeoForms
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UsersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for usersGet
     *
     * Get all users.
     *
     */
    public function testUsersGet()
    {
    }

    /**
     * Test case for usersPost
     *
     * Create a new user.
     *
     */
    public function testUsersPost()
    {
    }

    /**
     * Test case for usersUserIdDelete
     *
     * Delete a user.
     *
     */
    public function testUsersUserIdDelete()
    {
    }

    /**
     * Test case for usersUserIdPut
     *
     * Update a user.
     *
     */
    public function testUsersUserIdPut()
    {
    }
}
